SECRET_KEY="REPLACE_WITH_YOUR_SECRATE_KEY_OR_RUN_SETUP.PY"
SESSION_TOKENS_LIMIT=1024
MAX_FILE_UPLOAD_LIMIT=32
GIT_COMMAND_PATH = "git"
DOCKER_COMMAND_PATH = "docker"
MAX_FILES_ON_HOME = 128
SEARCH_INDEXING_TIME_DELAY = 5
